# Generated by Django 4.1 on 2022-08-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price, USD')),
                ('year_of_manufacture', models.IntegerField(verbose_name='Year Of Manufacture')),
                ('mileage_km', models.IntegerField(verbose_name='Mileage, km')),
                ('engine_capacity_liters', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Engine Capacity, liters')),
                ('num_seats', models.IntegerField(verbose_name='Seats In Vehicle')),
                ('num_doors', models.IntegerField(verbose_name='Doors In Vehicle')),
                ('description', models.TextField(blank=True, verbose_name='Vehicle Description')),
            ],
        ),
    ]
