# Generated by Django 4.1 on 2022-08-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBodyColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Vehicle Body Color')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Vehicle Brand')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEngineCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_capacity_liters', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Engine Capacity (liters)')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Fuel Type')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleNumDoors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_doors', models.IntegerField(verbose_name='Number Of Doors')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleNumSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_seats', models.IntegerField(verbose_name='Number Of Seats')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Transmission Type')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTypeOfDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Type Of Drive')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModelInBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Vehicle Model')),
                ('vehicle_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_fleet.vehiclebrand')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Price, USD')),
                ('year_of_manufacture', models.IntegerField(verbose_name='Year Of Manufacture')),
                ('mileage_km', models.IntegerField(verbose_name='Mileage, km')),
                ('description', models.TextField(blank=True, verbose_name='Vehicle Description')),
                ('body_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_fleet.vehiclebodycolor')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_fleet.vehiclebrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle_fleet.vehiclecategory')),
                ('engine_capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_fleet.vehicleenginecapacity')),
                ('fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_fleet.vehiclefuel')),
                ('model_in_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_fleet.vehiclemodelinbrand')),
                ('num_doors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_fleet.vehiclenumdoors')),
                ('num_seats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_fleet.vehiclenumseats')),
                ('transmission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_fleet.vehicletransmission')),
                ('type_of_drive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_fleet.vehicletypeofdrive')),
            ],
        ),
    ]
