# Generated by Django 4.1 on 2022-08-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Company Name')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Vehicle Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, verbose_name='Vehicle Model')),
                ('license_plate_num', models.CharField(max_length=10, verbose_name='License Plate Number')),
                ('vehicle_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Vehicle Type')),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True, verbose_name='Year Of Manufacture')),
                ('mileage_km', models.IntegerField(blank=True, null=True, verbose_name='Mileage, km')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Price, USD')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Vehicle Description')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_fleet.vehiclebrand')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_fleet.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('num_years_experience', models.IntegerField(blank=True, null=True, verbose_name='Years Of Experience')),
                ('is_driving', models.BooleanField(verbose_name='Is Driving')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_fleet.vehicle')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_fleet.enterprise')),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='managed_enterprises',
            field=models.ManyToManyField(blank=True, related_name='managers', to='vehicle_fleet.enterprise', verbose_name='Managed Enterprises'),
        ),
    ]
