# Generated by Django 4.1 on 2022-08-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_fleet', '0002_enterprise_driver_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='assigned_vehicles',
            field=models.ManyToManyField(to='vehicle_fleet.vehicle'),
        ),
    ]
