# Generated by Django 4.1 on 2022-08-26 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_fleet', '0003_driver_assigned_vehicles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='assigned_vehicles',
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_fleet.vehicle'),
        ),
    ]
